name: ci

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      MICROPYPATH: ".frozen:~/.micropython/lib:/usr/lib/micropython:$(pwd)"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git pkg-config libffi-dev
      - name: Build micropython
        run: |
          git clone --depth 1 https://github.com/micropython/micropython.git
          cd micropython
          git submodule update --init
          make -C mpy-cross
          make -C ports/unix
          cp ports/unix/build-standard/micropython ../bin
          cd ..
          rm -rf micropython
      - name: Install micropython dependencies
        run: cat requirements.txt test-requirements.txt | grep -v "^$" | xargs -n 1 ./bin/micropython -m mip install
      - name: Install the package
        run: ./bin/micropython -m mip install ./package.json
      - name: Run tests
        run: ./bin/micropython -m unittest
